/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareGuideRouteImport } from './routes/care-guide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AiAssessmentRouteImport } from './routes/ai.assessment'
import { Route as AiImageAnalysisRouteImport } from './routes/ai.image-analysis'
import { Route as AmbulanceIndexRouteImport } from './routes/ambulance.index'
import { Route as AmbulanceTrackingRouteImport } from './routes/ambulance.tracking'
import { Route as EmergencyIndexRouteImport } from './routes/emergency.index'
import { Route as EmergencyRequestRouteImport } from './routes/emergency.request'
import { Route as EmergencyTypeRouteImport } from './routes/emergency.type'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PaymentsBillsRouteImport } from './routes/payments.bills'
import { Route as PaymentsHistoryRouteImport } from './routes/payments.history'
import { Route as PaymentsReceiptsRouteImport } from './routes/payments.receipts'
import { Route as PaymentsScanRouteImport } from './routes/payments.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareGuideRoute = CareGuideRouteImport.update({
  id: '/care-guide',
  path: '/care-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssessmentRoute = AiAssessmentRouteImport.update({
  id: '/ai/assessment',
  path: '/ai/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImageAnalysisRoute = AiImageAnalysisRouteImport.update({
  id: '/ai/image-analysis',
  path: '/ai/image-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceIndexRoute = AmbulanceIndexRouteImport.update({
  id: '/ambulance/',
  path: '/ambulance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceTrackingRoute = AmbulanceTrackingRouteImport.update({
  id: '/ambulance/tracking',
  path: '/ambulance/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyIndexRoute = EmergencyIndexRouteImport.update({
  id: '/emergency/',
  path: '/emergency/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRequestRoute = EmergencyRequestRouteImport.update({
  id: '/emergency/request',
  path: '/emergency/request',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyTypeRoute = EmergencyTypeRouteImport.update({
  id: '/emergency/type',
  path: '/emergency/type',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsBillsRoute = PaymentsBillsRouteImport.update({
  id: '/payments/bills',
  path: '/payments/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsHistoryRoute = PaymentsHistoryRouteImport.update({
  id: '/payments/history',
  path: '/payments/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsReceiptsRoute = PaymentsReceiptsRouteImport.update({
  id: '/payments/receipts',
  path: '/payments/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsScanRoute = PaymentsScanRouteImport.update({
  id: '/payments/scan',
  path: '/payments/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care-guide': typeof CareGuideRoute
  '/dashboard': typeof DashboardRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/ai/assessment': typeof AiAssessmentRoute
  '/ai/image-analysis': typeof AiImageAnalysisRoute
  '/ambulance/tracking': typeof AmbulanceTrackingRoute
  '/emergency/request': typeof EmergencyRequestRoute
  '/emergency/type': typeof EmergencyTypeRoute
  '/payments/bills': typeof PaymentsBillsRoute
  '/payments/history': typeof PaymentsHistoryRoute
  '/payments/receipts': typeof PaymentsReceiptsRoute
  '/payments/scan': typeof PaymentsScanRoute
  '/ai/': typeof AiIndexRoute
  '/ambulance/': typeof AmbulanceIndexRoute
  '/emergency/': typeof EmergencyIndexRoute
  '/payments/': typeof PaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care-guide': typeof CareGuideRoute
  '/dashboard': typeof DashboardRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/ai/assessment': typeof AiAssessmentRoute
  '/ai/image-analysis': typeof AiImageAnalysisRoute
  '/ambulance/tracking': typeof AmbulanceTrackingRoute
  '/emergency/request': typeof EmergencyRequestRoute
  '/emergency/type': typeof EmergencyTypeRoute
  '/payments/bills': typeof PaymentsBillsRoute
  '/payments/history': typeof PaymentsHistoryRoute
  '/payments/receipts': typeof PaymentsReceiptsRoute
  '/payments/scan': typeof PaymentsScanRoute
  '/ai': typeof AiIndexRoute
  '/ambulance': typeof AmbulanceIndexRoute
  '/emergency': typeof EmergencyIndexRoute
  '/payments': typeof PaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care-guide': typeof CareGuideRoute
  '/dashboard': typeof DashboardRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/ai/assessment': typeof AiAssessmentRoute
  '/ai/image-analysis': typeof AiImageAnalysisRoute
  '/ambulance/tracking': typeof AmbulanceTrackingRoute
  '/emergency/request': typeof EmergencyRequestRoute
  '/emergency/type': typeof EmergencyTypeRoute
  '/payments/bills': typeof PaymentsBillsRoute
  '/payments/history': typeof PaymentsHistoryRoute
  '/payments/receipts': typeof PaymentsReceiptsRoute
  '/payments/scan': typeof PaymentsScanRoute
  '/ai/': typeof AiIndexRoute
  '/ambulance/': typeof AmbulanceIndexRoute
  '/emergency/': typeof EmergencyIndexRoute
  '/payments/': typeof PaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care-guide'
    | '/dashboard'
    | '/hospitals'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/register'
    | '/roles'
    | '/settings'
    | '/welcome'
    | '/ai/assessment'
    | '/ai/image-analysis'
    | '/ambulance/tracking'
    | '/emergency/request'
    | '/emergency/type'
    | '/payments/bills'
    | '/payments/history'
    | '/payments/receipts'
    | '/payments/scan'
    | '/ai/'
    | '/ambulance/'
    | '/emergency/'
    | '/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care-guide'
    | '/dashboard'
    | '/hospitals'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/register'
    | '/roles'
    | '/settings'
    | '/welcome'
    | '/ai/assessment'
    | '/ai/image-analysis'
    | '/ambulance/tracking'
    | '/emergency/request'
    | '/emergency/type'
    | '/payments/bills'
    | '/payments/history'
    | '/payments/receipts'
    | '/payments/scan'
    | '/ai'
    | '/ambulance'
    | '/emergency'
    | '/payments'
  id:
    | '__root__'
    | '/'
    | '/care-guide'
    | '/dashboard'
    | '/hospitals'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/register'
    | '/roles'
    | '/settings'
    | '/welcome'
    | '/ai/assessment'
    | '/ai/image-analysis'
    | '/ambulance/tracking'
    | '/emergency/request'
    | '/emergency/type'
    | '/payments/bills'
    | '/payments/history'
    | '/payments/receipts'
    | '/payments/scan'
    | '/ai/'
    | '/ambulance/'
    | '/emergency/'
    | '/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareGuideRoute: typeof CareGuideRoute
  DashboardRoute: typeof DashboardRoute
  HospitalsRoute: typeof HospitalsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  RegisterRoute: typeof RegisterRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  AiAssessmentRoute: typeof AiAssessmentRoute
  AiImageAnalysisRoute: typeof AiImageAnalysisRoute
  AmbulanceTrackingRoute: typeof AmbulanceTrackingRoute
  EmergencyRequestRoute: typeof EmergencyRequestRoute
  EmergencyTypeRoute: typeof EmergencyTypeRoute
  PaymentsBillsRoute: typeof PaymentsBillsRoute
  PaymentsHistoryRoute: typeof PaymentsHistoryRoute
  PaymentsReceiptsRoute: typeof PaymentsReceiptsRoute
  PaymentsScanRoute: typeof PaymentsScanRoute
  AiIndexRoute: typeof AiIndexRoute
  AmbulanceIndexRoute: typeof AmbulanceIndexRoute
  EmergencyIndexRoute: typeof EmergencyIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-guide': {
      id: '/care-guide'
      path: '/care-guide'
      fullPath: '/care-guide'
      preLoaderRoute: typeof CareGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/assessment': {
      id: '/ai/assessment'
      path: '/ai/assessment'
      fullPath: '/ai/assessment'
      preLoaderRoute: typeof AiAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/image-analysis': {
      id: '/ai/image-analysis'
      path: '/ai/image-analysis'
      fullPath: '/ai/image-analysis'
      preLoaderRoute: typeof AiImageAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance/': {
      id: '/ambulance/'
      path: '/ambulance'
      fullPath: '/ambulance/'
      preLoaderRoute: typeof AmbulanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance/tracking': {
      id: '/ambulance/tracking'
      path: '/ambulance/tracking'
      fullPath: '/ambulance/tracking'
      preLoaderRoute: typeof AmbulanceTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/': {
      id: '/emergency/'
      path: '/emergency'
      fullPath: '/emergency/'
      preLoaderRoute: typeof EmergencyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/request': {
      id: '/emergency/request'
      path: '/emergency/request'
      fullPath: '/emergency/request'
      preLoaderRoute: typeof EmergencyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/type': {
      id: '/emergency/type'
      path: '/emergency/type'
      fullPath: '/emergency/type'
      preLoaderRoute: typeof EmergencyTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/bills': {
      id: '/payments/bills'
      path: '/payments/bills'
      fullPath: '/payments/bills'
      preLoaderRoute: typeof PaymentsBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/history': {
      id: '/payments/history'
      path: '/payments/history'
      fullPath: '/payments/history'
      preLoaderRoute: typeof PaymentsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/receipts': {
      id: '/payments/receipts'
      path: '/payments/receipts'
      fullPath: '/payments/receipts'
      preLoaderRoute: typeof PaymentsReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/scan': {
      id: '/payments/scan'
      path: '/payments/scan'
      fullPath: '/payments/scan'
      preLoaderRoute: typeof PaymentsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareGuideRoute: CareGuideRoute,
  DashboardRoute: DashboardRoute,
  HospitalsRoute: HospitalsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  RegisterRoute: RegisterRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  AiAssessmentRoute: AiAssessmentRoute,
  AiImageAnalysisRoute: AiImageAnalysisRoute,
  AmbulanceTrackingRoute: AmbulanceTrackingRoute,
  EmergencyRequestRoute: EmergencyRequestRoute,
  EmergencyTypeRoute: EmergencyTypeRoute,
  PaymentsBillsRoute: PaymentsBillsRoute,
  PaymentsHistoryRoute: PaymentsHistoryRoute,
  PaymentsReceiptsRoute: PaymentsReceiptsRoute,
  PaymentsScanRoute: PaymentsScanRoute,
  AiIndexRoute: AiIndexRoute,
  AmbulanceIndexRoute: AmbulanceIndexRoute,
  EmergencyIndexRoute: EmergencyIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
